apiVersion: v1
kind: Template
labels:
  template: krakend-persistent-template
metadata:
  name: krakend-persistent
  annotations:
    description: KrakenD API Gateway persistent template
    tags: api,krakend,gateway,proxy
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/devopsfaith/krakend:${KRAKEND_VERSION}
      name: ${KRAKEND_VERSION}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: ${SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: CONTEXT_PATH
            value: /
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MAX_MEMORY}
            requests:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/krakend
            name: ${SERVICE_NAME}-etc
          - mountPath: /etc/krakend/krakend.json
            name: ${SERVICE_NAME}-config
            subPath: krakend.json
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
        volumes:
        - name: ${SERVICE_NAME}-etc
          persistentVolumeClaim:
            claimName: ${SERVICE_NAME}-etc-pv
        - name: ${SERVICE_NAME}-config
          configMap:
            name: krakend-config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:${KRAKEND_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    tls:
      termination: edge
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${SERVICE_NAME}
      weight: 100
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}-etc-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- displayName: KrakenD service name
  name: SERVICE_NAME
  required: true
  value: krakend
- displayName: KrakenD version
  name: KRAKEND_VERSION
  required: true
  value: 1.0.0
- description: Volume space available for KrakenD e.g. 512Mi, 2Gi
  displayName: Volume Space for KrakenD
  name: VOLUME_CAPACITY
  required: true
  value: 512Mi
- description: Max memory allocated to the KrakenD pod e.g. 512Mi, 2Gi
  displayName: Max Memory for KrakenD
  name: MAX_MEMORY
  required: true
  value: 512Mi